export const projects = [
  {
    id: 1,
    name: "L'Hirondelle",
    image: `${process.env.AWS_S3_BUCKET}/lhirondelle_project.png`,
    description: `Full redesign and migration of a Montreal nonprofit's website. Built with Bricks Builder on WordPress, with a fully restructured backend using ACF so the client could manage everything without touching code. Configured a multilingual setup across 4–5 languages with WPML, built an event and activity management system, integrated an appointment booking flow, and wired up PayPal for donation payments. Automated email confirmations with Make.com and wrote full documentation for the team.`,
    techstack: "WordPress · Bricks Builder · PHP · ACF · WPML · Make.com · Mailchimp · PayPal · DNS",
    github: null,
    website: "https://hirondelle.qc.ca/",
  },
  {
    id: 2,
    name: "BTH Expert",
    image: `${process.env.AWS_S3_BUCKET}/bthexpert_project.png`,
    description: `Designed and built a modern showcase website for an Algerian environmental engineering firm. The client needed something clean and fast — no heavy CMS, no maintenance overhead. Went with a static stack deployed on Netlify with Decap CMS as the backend, giving the client full control over every text, image, project, and sector entry through a simple admin interface. Set up DNS and configured transactional email end to end.`,
    techstack: "HTML · CSS · JavaScript · Netlify · Decap CMS · DNS",
    github: null,
    website: "https://bthexpert.com/",
  },
  {
    id: 3,
    name: "Laghata",
    image: `${process.env.AWS_S3_BUCKET}/laghata_project.png`,
    description: `Full stack marketplace connecting people who want to rent out their outdoor gear — surf, bikes, snowboards and more. Built the complete flow from listing creation to booking, payment and reviews. Real-time chat between users via Socket.io, JWT authentication with email verification, and image uploads via Cloudinary. Deployed in production on Render with MongoDB Atlas.`,
    techstack: "React · Node.js · Express · MongoDB · Socket.io · JWT · Cloudinary · AWS · Cypress",
    github: "https://github.com/Aymen-Gherdaine/laghata-marketplace",
    website: "https://laghata-marketplace-frontend.onrender.com",
  },
  {
    id: 4,
    name: "Portfolio",
    image: `${process.env.AWS_S3_BUCKET}/portfolio_project.png`,
    description: `Designed and built this portfolio from scratch using Next.js 14. Assets served from AWS S3, contact form wired to Resend for email delivery, dark/light theme switching, and continuous deployment on Netlify. Component-driven architecture with content fully separated from logic for easy updates.`,
    techstack: "Next.js · AWS S3 · Netlify · Resend · CSS Modules",
    github: "https://github.com/Aymen-Gherdaine/Portfolio",
    website: "https://aymengherdaine.dev",
  },
];